version: '3.7'

services:

  fluentd:
    image: fluentd:v1.14-1
    hostname: fluentd
    container_name: fluentd
    ports:
      - 8888:8888
    volumes:
      - ./log:/fluentd/log
      - ./in_http.conf:/fluentd/etc/fluent.conf
  
  fluentd-ui:
    image: fluentd-ui:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    hostname: fluentd
    container_name: fluentd-ui
    ports:
      - 9292:9292
  # user: admin
  # password: changeme
